Blocked access to external URL https://www.localhost:9443/fetch/api/resources/inspect-headers.py?cors&headers=referer

FAIL Request's referrer is origin promise_test: Unhandled rejection with value: object "TypeError: Type error"

